
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_demo_nov_development

test: &test
  <<: *default
  database: rails_demo_nov_test

production:
  <<: *default
  database: rails_demo_nov_production
  username: rails_demo_nov
  password: <%= ENV['RAILS_DEMO_NOV_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
