# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6568c7ca621283fa83e70d90260b8882412ab6b3163f04703a81ea6a253e450379a06712976afe7f9080c4d1472b92c11f7157fd4c0ccac05e6a424341c83fe9

test:
  secret_key_base: ecbfd3bda8f5aa6d1fa40f1ac0386606b829ed09f8ae082f0dd9daa4389a784c6b97ccf553461708fa77d8e78a48810c6b21915aced014ff03fed58be7ff0c5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
